### PR TITLE
New bot recode

### PR DESCRIPTION
**Pull request by callumok2004**

### CODE REVIEW

**Comment by callumok2004** [comment]
Retry DeepCode

**Comment by callumok2004** [comment]
I broke Deep code.... ern

**Comment by callumok2004** [comment]
Retry DeepCode

**Comment by Bas950** [comment]
Why are you deleting the docker files and the license file??

**Comment by callumok2004** [comment]
> Why are you deleting the docker files and the license file??

Ill add them back, remember I did start from scratch without any of the old files, new folder new everything lol

**Comment by callumok2004** [comment]
everyone needs to scream @Timeraa to review and accept!! amiright

**Comment by Timeraa** [comment]
# So that we have this Pull Request sorted out:

**We will not accept & merge it due to these reasons:**
- When you started the recode I was literally on the same day thinking of simplifying it
- When we started our Staff Backend we already had in mind of creating a bot for it, which would replace the PreMiD Bot therefore rendering this recode useless, as that bot would have a lot of private functions and the support system would be integrated into it
- ^ Adding onto this the bot would be private as this one does not have anything useful in it anyways.
- A lot of current functions would be moved onto the new Staff Backend
- Error handling would be greatly improved with our hosted instance of Sentry
- Your commit messages are not really up to standard
- Your coding style does not really fit standards, for example try catching important actions

As a quick note, we will be working on the mentioned bot today/tomorrow as part of the first step on the posted roadmap. It will be released shortly after that and will then replace the current bot.

~ Timeraa, Bas950

**Pull request closed without merging**
